"""Bergamo-specific DE/FR phrase replacements for seller landing page."""

from __future__ import annotations

PHRASES_BERGAMO_DE: list[tuple[str, str]] = [
    ("Sono un Agente Immobiliare affiliato RE/MAX con background da geometra e imprenditore. Conosco le specificit&agrave; di ogni zona del territorio bergamasco &mdash; dalla Citt&agrave; Alta al tessuto residenziale della Bassa, dalla Valle Seriana ai comuni di cintura. Ogni micro-mercato ha regole proprie.",
     "Als RE/MAX-Immobilienberater mit Hintergrund als Vermessungsingenieur und Unternehmer kenne ich die Besonderheiten jeder Zone im Bergamasco &mdash; von der Citt&agrave; Alta bis zum Wohngebiet der Bassa, von der Valle Seriana bis zu den Vorortgemeinden. Jeder Mikromarkt hat eigene Regeln."),
    ("Dal centro di Bergamo a Citt&agrave; Alta, dalla Valle Seriana alla Bassa, ogni zona ha dinamiche proprie. <strong>Un prezzo sbagliato pu&ograve; costarti mesi sul mercato</strong> o migliaia di euro nella trattativa. Prima della vendita, servono dati reali, metodo e posizionamento corretto.",
     "Vom Zentrum Bergamos bis zur Citt&agrave; Alta, von der Valle Seriana bis zur Bassa &mdash; jede Zone hat eigene Dynamiken. <strong>Ein falscher Preis kann Sie Monate auf dem Markt kosten</strong> oder in der Verhandlung Tausende Euro. Vor dem Verkauf brauchen Sie echte Daten, Methode und die richtige Positionierung."),
    ("Sono un Agente Immobiliare affiliato RE/MAX con background da geometra e imprenditore. Conosco le specificità di ogni zona del territorio bergamasco — dalla Città Alta al tessuto residenziale della Bassa, dalla Valle Seriana ai comuni di cintura. Ogni micro-mercato ha regole proprie.",
     "Als RE/MAX-Immobilienberater mit Hintergrund als Vermessungsingenieur und Unternehmer kenne ich die Besonderheiten jeder Zone im Bergamasco — von der Città Alta bis zum Wohngebiet der Bassa, von der Valle Seriana bis zu den Vorortgemeinden. Jeder Mikromarkt hat eigene Regeln."),
    ("Dal centro di Bergamo a Città Alta, dalla Valle Seriana alla Bassa, ogni zona ha dinamiche proprie. <strong>Un prezzo sbagliato può costarti mesi sul mercato</strong> o migliaia di euro nella trattativa. Prima della vendita, servono dati reali, metodo e posizionamento corretto.",
     "Vom Zentrum Bergamos bis zur Città Alta, von der Valle Seriana bis zur Bassa — jede Zone hat eigene Dynamiken. <strong>Ein falscher Preis kann Sie Monate auf dem Markt kosten</strong> oder in der Verhandlung Tausende Euro. Vor dem Verkauf brauchen Sie echte Daten, Methode und die richtige Positionierung."),
    ("Un appartamento in Citt&agrave; Alta non segue le stesse dinamiche di un trilocale in Citt&agrave; Bassa, di una casa in Valle Seriana o di un immobile nei comuni di cintura verso Milano. Per questo ogni analisi deve essere costruita sulla zona reale dell'immobile.",
     "Eine Wohnung in der Citt&agrave; Alta folgt nicht denselben Dynamiken wie ein Dreizimmer in der Citt&agrave; Bassa, ein Haus in der Valle Seriana oder eine Immobilie in Vorortgemeinden Richtung Mailand. Deshalb muss jede Analyse auf der tatsächlichen Zone der Immobilie basieren."),
    ("Le stime automatiche non vedono stato interno, piano, affaccio, criticit&agrave; documentali e domanda reale della zona. A Bergamo la differenza tra Citt&agrave; Alta e Citt&agrave; Bassa, o tra i vari quartieri, pu&ograve; incidere significativamente sul valore.",
     "Automatische Schätzungen berücksichtigen weder Innenzustand, Etage, Ausrichtung, dokumentarische Risiken noch die reale Nachfrage in der Zone. In Bergamo kann der Unterschied zwischen Citt&agrave; Alta und Citt&agrave; Bassa oder zwischen den einzelnen Quartieren den Wert erheblich beeinflussen."),
    ("Un appartamento in Città Alta non segue le stesse dinamiche di un trilocale in Città Bassa, di una casa in Valle Seriana o di un immobile nei comuni di cintura verso Milano. Per questo ogni analisi deve essere costruita sulla zona reale dell'immobile.",
     "Eine Wohnung in der Città Alta folgt nicht denselben Dynamiken wie ein Dreizimmer in der Città Bassa, ein Haus in der Valle Seriana oder eine Immobilie in Vorortgemeinden Richtung Mailand. Deshalb muss jede Analyse auf der tatsächlichen Zone der Immobilie basieren."),
    ("La mia consulenza rimane personale e diretta. L'affiliazione RE/MAX aggiunge autorit&agrave;, rete e maggiore visibilit&agrave; &mdash; anche per acquirenti che si spostano da Milano verso Bergamo e per chi cerca soluzioni sul Lago d'Iseo bergamasco.",
     "Meine Beratung bleibt persönlich und direkt. Die RE/MAX-Affiliation verleiht Autorität, Netzwerk und mehr Sichtbarkeit &mdash; auch für Käufer, die von Mailand nach Bergamo ziehen, und für alle, die am Bergamasker Iseosee suchen."),
    ("agente immobiliare Bergamo, agente RE/MAX Bergamo, valutazione casa Bergamo, vendere casa Bergamo, agente immobiliare Citt&agrave; Alta, agente immobiliare provincia Bergamo, valutazione immobile Bergamo, Maurizio Piraino immobiliare Bergamo",
     "Immobilienberater Bergamo, RE/MAX-Berater Bergamo, Immobilienbewertung Bergamo, Haus verkaufen Bergamo, Immobilienberater Citt&agrave; Alta, Immobilienberater Provinz Bergamo, Immobilienbewertung Bergamo, Maurizio Piraino Immobilien Bergamo"),
    ("Dovevo gestire la vendita di una casa in provincia ereditata. Il background tecnico da geometra ha individuato subito una difformit&agrave; catastale che avrebbe bloccato il rogito. Risolta prima delle visite, vendita conclusa regolarmente.",
     "Ich musste den Verkauf eines geerbten Hauses in der Provinz organisieren. Der technische Hintergrund als Vermessungsingenieur deckte sofort eine Katasterabweichung auf, die den Notartermin blockiert hätte. Vor den Besichtigungen gelöst &mdash; regulärer Verkaufsabschluss."),
    ("Le stime automatiche non vedono stato interno, piano, affaccio, criticità documentali e domanda reale della zona. A Bergamo la differenza tra Città Alta e Città Bassa, o tra i vari quartieri, può incidere significativamente sul valore.",
     "Automatische Schätzungen berücksichtigen weder Innenzustand, Etage, Ausrichtung, dokumentarische Risiken noch die reale Nachfrage in der Zone. In Bergamo kann der Unterschied zwischen Città Alta und Città Bassa oder zwischen den einzelnen Quartieren den Wert erheblich beeinflussen."),
    ("agente immobiliare Bergamo, agente RE/MAX Bergamo, valutazione casa Bergamo, vendere casa Bergamo, agente immobiliare Città Alta, agente immobiliare provincia Bergamo, valutazione immobile Bergamo, Maurizio Piraino immobiliare Bergamo",
     "Immobilienberater Bergamo, RE/MAX-Berater Bergamo, Immobilienbewertung Bergamo, Haus verkaufen Bergamo, Immobilienberater Città Alta, Immobilienberater Provinz Bergamo, Immobilienbewertung Bergamo, Maurizio Piraino Immobilien Bergamo"),
    ("Dovevo gestire la vendita di una casa in provincia ereditata. Il background tecnico da geometra ha individuato subito una difformità catastale che avrebbe bloccato il rogito. Risolta prima delle visite, vendita conclusa regolarmente.",
     "Ich musste den Verkauf eines geerbten Hauses in der Provinz organisieren. Der technische Hintergrund als Vermessungsingenieur deckte sofort eine Katasterabweichung auf, die den Notartermin blockiert hätte. Vor den Besichtigungen gelöst — regulärer Verkaufsabschluss."),
    ("La mia consulenza rimane personale e diretta. L'affiliazione RE/MAX aggiunge autorità, rete e maggiore visibilità — anche per acquirenti che si spostano da Milano verso Bergamo e per chi cerca soluzioni sul Lago d'Iseo bergamasco.",
     "Meine Beratung bleibt persönlich und direkt. Die RE/MAX-Affiliation verleiht Autorität, Netzwerk und mehr Sichtbarkeit — auch für Käufer, die von Mailand nach Bergamo ziehen, und für alle, die am Bergamasker Iseosee suchen."),
    ("Avevo provato a vendere il mio appartamento da solo per quasi sei mesi senza risultati concreti. L'analisi del micro-mercato della mia zona e il posizionamento corretto del prezzo hanno cambiato tutto. Chiuso in poche settimane.",
     "Ich hatte fast sechs Monate lang versucht, meine Wohnung allein zu verkaufen — ohne konkretes Ergebnis. Die Mikromarkt-Analyse meiner Zone und die korrekte Preispositionierung haben alles verändert. Abschluss in wenigen Wochen."),
    ("La mia casa a Treviglio era sul mercato da mesi. Il problema non era l'immobile, ma il posizionamento sbagliato per quella zona. Con la strategia giusta e gli acquirenti profilati correttamente, abbiamo chiuso in tempi brevi.",
     "Mein Haus in Treviglio stand seit Monaten am Markt. Das Problem war nicht die Immobilie, sondern die falsche Positionierung für diese Zone. Mit der richtigen Strategie und passend profilierten Käufern schlossen wir schnell ab."),
    ("La maggior parte degli agenti tratta tutto allo stesso modo. Io costruisco una strategia su misura per la zona specifica &mdash; Bergamo centro, collina, provincia &mdash; prima ancora di pubblicare la prima foto.",
     "Die meisten Makler behandeln alles gleich. Ich entwickle eine maßgeschneiderte Strategie für die konkrete Zone &mdash; Bergamo Zentrum, Hügel, Provinz &mdash; noch bevor das erste Foto veröffentlicht wird."),
    ("Vuoi capire su quali dati si basa il prezzo e distinguere una stima seria da una promessa &mdash; specialmente quando le valutazioni variano tra Citt&agrave; Alta, la Citt&agrave; Bassa e i comuni in provincia.",
     "Sie möchten verstehen, worauf der Preis basiert, und eine seriöse Schätzung von einer leeren Zusage unterscheiden &mdash; besonders wenn die Bewertungen zwischen Citt&agrave; Alta, Citt&agrave; Bassa und Provinzgemeinden variieren."),
    ("Mesi online, poche visite, offerte basse: spesso il problema non &egrave; la casa, ma il posizionamento sbagliato per quella zona &mdash; che a Bergamo cambia significativamente tra centro, collina e pianura.",
     "Monate online, wenige Besichtigungen, niedrige Angebote: oft liegt es nicht an der Immobilie, sondern an der falschen Positionierung für diese Zone &mdash; die in Bergamo zwischen Zentrum, Hügel und Ebene deutlich variiert."),
    ("La maggior parte degli agenti tratta tutto allo stesso modo. Io costruisco una strategia su misura per la zona specifica — Bergamo centro, collina, provincia — prima ancora di pubblicare la prima foto.",
     "Die meisten Makler behandeln alles gleich. Ich entwickle eine maßgeschneiderte Strategie für die konkrete Zone — Bergamo Zentrum, Hügel, Provinz — noch bevor das erste Foto veröffentlicht wird."),
    ("S&igrave;. Opero su tutto il territorio bergamasco &mdash; Bergamo citt&agrave;, Citt&agrave; Alta, Valle Seriana, Valle Brembana, comuni di cintura e Bassa bergamasca. Ogni zona ha dinamiche proprie.",
     "Ja. Ich arbeite im gesamten Bergamasco &mdash; Bergamo Stadt, Citt&agrave; Alta, Valle Seriana, Valle Brembana, Vorortgemeinden und Bassa bergamasca. Jede Zone hat eigene Dynamiken."),
    ("Mesi online, poche visite, offerte basse: spesso il problema non è la casa, ma il posizionamento sbagliato per quella zona — che a Bergamo cambia significativamente tra centro, collina e pianura.",
     "Monate online, wenige Besichtigungen, niedrige Angebote: oft liegt es nicht an der Immobilie, sondern an der falschen Positionierung für diese Zone — die in Bergamo zwischen Zentrum, Hügel und Ebene deutlich variiert."),
    ("Vuoi capire su quali dati si basa il prezzo e distinguere una stima seria da una promessa — specialmente quando le valutazioni variano tra Città Alta, la Città Bassa e i comuni in provincia.",
     "Sie möchten verstehen, worauf der Preis basiert, und eine seriöse Schätzung von einer leeren Zusage unterscheiden — besonders wenn die Bewertungen zwischen Città Alta, Città Bassa und Provinzgemeinden variieren."),
    ("S&igrave;. Sapere oggi quanto vale il tuo immobile ti permette di pianificare senza pressione, scegliere il momento migliore e non farti trovare impreparato quando decidi di procedere.",
     "Ja. Den heutigen Wert Ihrer Immobilie zu kennen, ermöglicht Planung ohne Druck, die Wahl des besten Zeitpunkts &mdash; und dass Sie nicht unvorbereitet sind, wenn Sie sich entscheiden."),
    ("Dalla prima analisi alla possibile strategia di vendita: ogni fase &egrave; chiara, definita e concordata con te &mdash; ovunque si trovi il tuo immobile nel territorio bergamasco.",
     "Von der Erstanalyse bis zur möglichen Verkaufsstrategie: jede Phase ist klar, definiert und mit Ihnen abgestimmt &mdash; wo auch immer Ihre Immobilie im Bergamasco liegt."),
    ("Opero su Bergamo citt&agrave; e provincia e, tramite RE/MAX, posso coordinarmi anche con colleghi nelle altre province lombarde se il tuo immobile o il tuo obiettivo lo richiede.",
     "Ich arbeite in Bergamo Stadt und Provinz und kann über RE/MAX auch mit Kollegen in anderen Provinzen der Lombardei koordinieren, wenn Ihre Immobilie oder Ihr Ziel es erfordert."),
    ("Ti mostro il mercato reale della tua zona, le criticit&agrave; dell'immobile e la strategia pi&ugrave; adatta per Bergamo e provincia &mdash; prima ancora di parlare di incarico.",
     "Ich zeige Ihnen den realen Markt Ihrer Zone, die Risiken der Immobilie und die passende Strategie für Bergamo und Provinz &mdash; bevor wir über ein Mandat sprechen."),
    ("Sì. Sapere oggi quanto vale il tuo immobile ti permette di pianificare senza pressione, scegliere il momento migliore e non farti trovare impreparato quando decidi di procedere.",
     "Ja. Den heutigen Wert Ihrer Immobilie zu kennen, ermöglicht Planung ohne Druck, die Wahl des besten Zeitpunkts — und dass Sie nicht unvorbereitet sind, wenn Sie sich entscheiden."),
    ("&quot;A Bergamo, Citt&agrave; Alta e la Citt&agrave; Bassa sono due mercati diversi. Conoscere questa differenza prima del lancio vale migliaia di euro sulla trattativa.&quot;",
     "&quot;In Bergamo sind Citt&agrave; Alta und Citt&agrave; Bassa zwei verschiedene Märkte. Diesen Unterschied vor dem Marktstart zu kennen, ist in der Verhandlung Tausende Euro wert.&quot;"),
    ("Sì. Opero su tutto il territorio bergamasco — Bergamo città, Città Alta, Valle Seriana, Valle Brembana, comuni di cintura e Bassa bergamasca. Ogni zona ha dinamiche proprie.",
     "Ja. Ich arbeite im gesamten Bergamasco — Bergamo Stadt, Città Alta, Valle Seriana, Valle Brembana, Vorortgemeinden und Bassa bergamasca. Jede Zone hat eigene Dynamiken."),
    ("Opero su Bergamo città e provincia e, tramite RE/MAX, posso coordinarmi anche con colleghi nelle altre province lombarde se il tuo immobile o il tuo obiettivo lo richiede.",
     "Ich arbeite in Bergamo Stadt und Provinz und kann über RE/MAX auch mit Kollegen in anderen Provinzen der Lombardei koordinieren, wenn Ihre Immobilie oder Ihr Ziel es erfordert."),
    ("Agente Immobiliare affiliato RE/MAX &middot; REA BS-639579 &middot; P.IVA 14597560961 &middot; Bergamo &middot; Citt&agrave; Alta &middot; Valle Seriana &middot; Provincia",
     "RE/MAX-Immobilienberater &middot; REA BS-639579 &middot; USt-IdNr. 14597560961 &middot; Bergamo &middot; Citt&agrave; Alta &middot; Valle Seriana &middot; Provinz"),
    ("Dalla prima analisi alla possibile strategia di vendita: ogni fase è chiara, definita e concordata con te — ovunque si trovi il tuo immobile nel territorio bergamasco.",
     "Von der Erstanalyse bis zur möglichen Verkaufsstrategie: jede Phase ist klar, definiert und mit Ihnen abgestimmt — wo auch immer Ihre Immobilie im Bergamasco liegt."),
    ("Ogni vendita ha criticit&agrave; diverse. Il primo passo &egrave; capire cosa pu&ograve; rallentare, svalutare o valorizzare il tuo immobile nel territorio bergamasco.",
     "Jeder Verkauf hat andere Herausforderungen. Der erste Schritt: verstehen, was Ihre Immobilie im Bergamasco verzögern, entwerten oder aufwerten kann."),
    ("Ti mostro il mercato reale della tua zona, le criticità dell'immobile e la strategia più adatta per Bergamo e provincia — prima ancora di parlare di incarico.",
     "Ich zeige Ihnen den realen Markt Ihrer Zone, die Risiken der Immobilie und die passende Strategie für Bergamo und Provinz — bevor wir über ein Mandat sprechen."),
    ("Un marchio riconoscibile rassicura i proprietari e gli acquirenti &mdash; anche da fuori provincia e da acquirenti che si spostano da Milano verso Bergamo.",
     "Eine wiedererkennbare Marke schafft Vertrauen bei Eigentümern und Käufern &mdash; auch von außerhalb der Provinz und bei Käufern, die von Mailand nach Bergamo ziehen."),
    ("\"A Bergamo, Città Alta e la Città Bassa sono due mercati diversi. Conoscere questa differenza prima del lancio vale migliaia di euro sulla trattativa.\"",
     "&quot;In Bergamo sind Città Alta und Città Bassa zwei verschiedene Märkte. Diesen Unterschied vor dem Marktstart zu kennen, ist in der Verhandlung Tausende Euro wert.&quot;"),
    ("Vuoi vendere casa a Bergamo, in Citt&agrave; Alta o in provincia? Ricevi un'analisi immobiliare riservata basata su dati reali e strategia di vendita.",
     "Möchten Sie in Bergamo, in der Citt&agrave; Alta oder in der Provinz verkaufen? Erhalten Sie eine vertrauliche Immobilienanalyse auf realen Daten und Verkaufsstrategie."),
    ("Un marchio riconoscibile rassicura i proprietari e gli acquirenti — anche da fuori provincia e da acquirenti che si spostano da Milano verso Bergamo.",
     "Eine wiedererkennbare Marke schafft Vertrauen bei Eigentümern und Käufern — auch von außerhalb der Provinz und bei Käufern, die von Mailand nach Bergamo ziehen."),
    ("La collaborazione tra professionisti amplia le possibilit&agrave; di intercettare acquirenti qualificati, anche dal milanese e da fuori provincia.",
     "Die Zusammenarbeit zwischen Profis erweitert die Möglichkeiten, qualifizierte Käufer zu erreichen &mdash; auch aus dem Mailänder Raum und von außerhalb der Provinz."),
    ("Ogni vendita ha criticità diverse. Il primo passo è capire cosa può rallentare, svalutare o valorizzare il tuo immobile nel territorio bergamasco.",
     "Jeder Verkauf hat andere Herausforderungen. Der erste Schritt: verstehen, was Ihre Immobilie im Bergamasco verzögern, entwerten oder aufwerten kann."),
    ("Comuni come Dalmine, Seriate e Treviglio attraggono chi cerca pi&ugrave; spazio rispetto a Milano o Bergamo, con ottimi collegamenti ferroviari.",
     "Gemeinden wie Dalmine, Seriate und Treviglio ziehen an, wer mehr Raum als in Mailand oder Bergamo sucht &mdash; mit guten Bahnverbindungen."),
    ("Vuoi vendere casa a Bergamo, in Città Alta o in provincia? Ricevi un'analisi immobiliare riservata basata su dati reali e strategia di vendita.",
     "Möchten Sie in Bergamo, in der Città Alta oder in der Provinz verkaufen? Erhalten Sie eine vertrauliche Immobilienanalyse auf realen Daten und Verkaufsstrategie."),
    ("Definiamo prezzo, timing, comunicazione e profilo dell'acquirente pi&ugrave; adatto alla tua zona specifica &mdash; Bergamo, valli o provincia.",
     "Wir definieren Preis, Timing, Kommunikation und das passende Käuferprofil für Ihre konkrete Zone &mdash; Bergamo, Täler oder Provinz."),
    ("Domanda solida, con forte interesse da acquirenti milanesi. Citt&agrave; Alta e Citt&agrave; Bassa hanno dinamiche di prezzo molto differenti.",
     "Solide Nachfrage mit starkem Interesse mailändischer Käufer. Citt&agrave; Alta und Citt&agrave; Bassa haben sehr unterschiedliche Preisdynamiken."),
    ("La collaborazione tra professionisti amplia le possibilità di intercettare acquirenti qualificati, anche dal milanese e da fuori provincia.",
     "Die Zusammenarbeit zwischen Profis erweitert die Möglichkeiten, qualifizierte Käufer zu erreichen — auch aus dem Mailänder Raum und von außerhalb der Provinz."),
    ("Comuni come Dalmine, Seriate e Treviglio attraggono chi cerca più spazio rispetto a Milano o Bergamo, con ottimi collegamenti ferroviari.",
     "Gemeinden wie Dalmine, Seriate und Treviglio ziehen an, wer mehr Raum als in Mailand oder Bergamo sucht — mit guten Bahnverbindungen."),
    ("Valle Seriana e Valle Brembana attraggono chi cerca qualit&agrave; di vita, verde e prezzi pi&ugrave; accessibili rispetto al capoluogo.",
     "Valle Seriana und Valle Brembana ziehen an, wer Lebensqualität, Grün und erschwinglichere Preise als in der Provinzhauptstadt sucht."),
    ("Vendere casa a Bergamo, in Citt&agrave; Alta o in provincia? Analisi immobiliare riservata su dati reali, prima di parlare di incarico.",
     "Haus verkaufen in Bergamo, in der Citt&agrave; Alta oder in der Provinz? Vertrauliche Immobilienanalyse auf realen Daten &mdash; bevor wir über ein Mandat sprechen."),
    ("Prima di decidere, vuoi leggere il mercato reale della tua zona &mdash; Bergamo, valle o provincia &mdash; e non muoverti a sensazione.",
     "Bevor Sie entscheiden, möchten Sie den realen Markt Ihrer Zone lesen &mdash; Bergamo, Tal oder Provinz &mdash; und nicht nach Gefühl handeln."),
    ("Confronti zona per zona &mdash; Citt&agrave; Alta, Citt&agrave; Bassa, valli, pianura &mdash; e posizionamento corretto del prezzo.",
     "Vergleiche Zone für Zone &mdash; Citt&agrave; Alta, Citt&agrave; Bassa, Täler, Ebene &mdash; und korrekte Preispositionierung."),
    ("Definiamo prezzo, timing, comunicazione e profilo dell'acquirente più adatto alla tua zona specifica — Bergamo, valli o provincia.",
     "Wir definieren Preis, Timing, Kommunikation und das passende Käuferprofil für Ihre konkrete Zone — Bergamo, Täler oder Provinz."),
    ("Vendere casa a Bergamo, in Città Alta o in provincia? Analisi immobiliare riservata su dati reali, prima di parlare di incarico.",
     "Haus verkaufen in Bergamo, in der Città Alta oder in der Provinz? Vertrauliche Immobilienanalyse auf realen Daten — bevor wir über ein Mandat sprechen."),
    ("Domanda solida, con forte interesse da acquirenti milanesi. Città Alta e Città Bassa hanno dinamiche di prezzo molto differenti.",
     "Solide Nachfrage mit starkem Interesse mailändischer Käufer. Città Alta und Città Bassa haben sehr unterschiedliche Preisdynamiken."),
    ("&Egrave; un confronto strutturato sul tuo immobile, sulla micro-zona e sulla strategia di vendita pi&ugrave; adatta a Bergamo.",
     "Es ist ein strukturierter Vergleich Ihrer Immobilie, der Mikrozone und der für Bergamo passendsten Verkaufsstrategie."),
    ("Prima di firmare qualsiasi cosa, vuoi una strategia chiara, riservata e costruita sulla realt&agrave; del mercato bergamasco.",
     "Bevor Sie etwas unterschreiben, möchten Sie eine klare, vertrauliche Strategie, die auf der Realität des Bergamasker Marktes basiert."),
    ("Prima di decidere, vuoi leggere il mercato reale della tua zona — Bergamo, valle o provincia — e non muoverti a sensazione.",
     "Bevor Sie entscheiden, möchten Sie den realen Markt Ihrer Zone lesen — Bergamo, Tal oder Provinz — und nicht nach Gefühl handeln."),
    ("Valle Seriana e Valle Brembana attraggono chi cerca qualità di vita, verde e prezzi più accessibili rispetto al capoluogo.",
     "Valle Seriana und Valle Brembana ziehen an, wer Lebensqualität, Grün und erschwinglichere Preise als in der Provinzhauptstadt sucht."),
    ("Leggo l'immobile, la zona specifica e ti mostro dati, criticit&agrave; e potenzialit&agrave; prima di parlare di incarico.",
     "Ich lese die Immobilie und die konkrete Zone und zeige Ihnen Daten, Risiken und Potenziale &mdash; bevor wir über ein Mandat sprechen."),
    ("Agente Immobiliare affiliato RE/MAX · REA BS-639579 · P.IVA 14597560961 · Bergamo · Città Alta · Valle Seriana · Provincia",
     "RE/MAX-Immobilienberater · REA BS-639579 · USt-IdNr. 14597560961 · Bergamo · Città Alta · Valle Seriana · Provinz"),
    ("Prima di firmare qualsiasi cosa, vuoi una strategia chiara, riservata e costruita sulla realtà del mercato bergamasco.",
     "Bevor Sie etwas unterschreiben, möchten Sie eine klare, vertrauliche Strategie, die auf der Realität des Bergamasker Marktes basiert."),
    ("Bergamo Alta, Borgo Palazzo, Val Seriana e i comuni della provincia hanno dinamiche di prezzo molto diverse tra loro.",
     "Bergamo Alta, Borgo Palazzo, Val Seriana und die Provinzgemeinden haben sehr unterschiedliche Preisdynamiken."),
    ("La differenza resta nel modo in cui l'immobile viene analizzato, posizionato e presentato per la sua zona specifica.",
     "Der Unterschied liegt darin, wie die Immobilie für ihre konkrete Zone analysiert, positioniert und präsentiert wird."),
    ("È un confronto strutturato sul tuo immobile, sulla micro-zona e sulla strategia di vendita più adatta a Bergamo.",
     "Es ist ein strukturierter Vergleich Ihrer Immobilie, der Mikrozone und der für Bergamo passendsten Verkaufsstrategie."),
    ("Leggo l'immobile, la zona specifica e ti mostro dati, criticità e potenzialità prima di parlare di incarico.",
     "Ich lese die Immobilie und die konkrete Zone und zeige Ihnen Daten, Risiken und Potenziale — bevor wir über ein Mandat sprechen."),
    ("Confronti zona per zona — Città Alta, Città Bassa, valli, pianura — e posizionamento corretto del prezzo.",
     "Vergleiche Zone für Zone — Città Alta, Città Bassa, Täler, Ebene — und korrekte Preispositionierung."),
    ("Se decidi di procedere, ti accompagno in visite, offerte, trattativa e passaggi tecnici fino al rogito.",
     "Wenn Sie fortfahren, begleite ich Sie bei Besichtigungen, Angeboten, Verhandlung und technischen Schritten bis zum Notartermin."),
    ("Agente Immobiliare affiliato RE/MAX &middot; Bergamo &middot; Citt&agrave; Alta &middot; Provincia",
     "RE/MAX-Immobilienberater &middot; Bergamo &middot; Citt&agrave; Alta &middot; Provinz"),
    ("Prima casa, seconda casa, investimento: ogni profilo richiede comunicazione e target differenti.",
     "Erstwohnung, Zweitwohnung, Investition: jedes Profil braucht andere Kommunikation und Zielgruppe."),
    ("Agente Immobiliare affiliato RE/MAX. Consulenza per venditori e acquirenti in Lombardia.",
     "RE/MAX-Immobilienberater. Beratung für Verkäufer und Käufer in der Lombardei."),
    ("Analisi immobiliare riservata per vendere casa a Bergamo, Citt&agrave; Alta e provincia.",
     "Vertrauliche Immobilienanalyse zum Verkauf in Bergamo, Citt&agrave; Alta und Provinz."),
    ("Dalla prima visita alla firma dal notaio, senza improvvisazione e senza lasciarti solo.",
     "Von der ersten Besichtigung bis zur notariellen Beurkundung — ohne Improvisation und ohne Sie allein zu lassen."),
    ("Analisi immobiliare riservata per vendere casa a Bergamo, Città Alta e provincia.",
     "Vertrauliche Immobilienanalyse zum Verkauf in Bergamo, Città Alta und Provinz."),
    ("Prima di vendere casa a Bergamo o in provincia, serve capire davvero quanto vale.",
     "Bevor Sie in Bergamo oder in der Provinz verkaufen, müssen Sie den realen Wert Ihrer Immobilie kennen."),
    ("Valutazione riservata su Bergamo, valli e provincia. Nessun obbligo di incarico.",
     "Vertrauliche Bewertung für Bergamo, Täler und Provinz. Keine Verpflichtung zum Mandat."),
    ("A Bergamo e provincia, vendere bene non &egrave; fortuna. &Egrave; strategia.",
     "In Bergamo und Provinz ist gut verkaufen kein Glück &mdash; es ist Strategie."),
    ("Bergamo &middot; Citt&agrave; Alta &middot; Valle Seriana &middot; Provincia",
     "Bergamo &middot; Citt&agrave; Alta &middot; Valle Seriana &middot; Provinz"),
    ("Comprare a Bergamo senza pagare troppo. Analisi OMI e verifica tecnica.",
     "In Bergamo kaufen, ohne zu viel zu zahlen. OMI-Analyse und technische Prüfung."),
    ("Agente Immobiliare affiliato RE/MAX · Bergamo · Città Alta · Provincia",
     "RE/MAX-Immobilienberater · Bergamo · Città Alta · Provinz"),
    ("Scrivi zona o comune (es. Citt&agrave; Alta, Seriate, Treviglio...)",
     "Zone oder Gemeinde eingeben (z. B. Citt&agrave; Alta, Seriate, Treviglio …)"),
    ("Agente Immobiliare affiliato RE/MAX &middot; Bergamo e Provincia",
     "RE/MAX-Immobilienberater &middot; Bergamo und Provinz"),
    ("Agente Immobiliare Bergamo | Valutazione Casa &middot; Piraino",
     "Immobilienberater Bergamo | Immobilienbewertung &middot; Piraino"),
    ("Agente Immobiliare affiliato RE/MAX Bergamo | Valutazione Casa",
     "RE/MAX-Immobilienberater Bergamo | Immobilienbewertung"),
    ("&middot; Bergamo &middot; Citt&agrave; Alta &middot; Provincia",
     "&middot; Bergamo &middot; Citt&agrave; Alta &middot; Provinz"),
    ("Scrivi zona o comune (es. Città Alta, Seriate, Treviglio...)",
     "Zone oder Gemeinde eingeben (z. B. Città Alta, Seriate, Treviglio …)"),
    ("Bergamo cambia zona per zona. Ogni mercato ha le sue regole.",
     "Bergamo ändert sich von Zone zu Zone. Jeder Markt hat seine eigenen Regeln."),
    ("Maurizio Piraino Agente Immobiliare affiliato RE/MAX Bergamo",
     "Maurizio Piraino RE/MAX-Immobilienberater Bergamo"),
    ("Agente Immobiliare affiliato RE/MAX · Bergamo e Provincia",
     "RE/MAX-Immobilienberater · Bergamo und Provinz"),
    ("Un prezzo sbagliato pu&ograve; costarti mesi sul mercato",
     "Ein falscher Preis kann Sie Monate auf dem Markt kosten"),
    ("Agente Immobiliare Bergamo | Valutazione Casa · Piraino",
     "Immobilienberater Bergamo | Immobilienbewertung · Piraino"),
    ("Consulta i valori OMI ufficiali per zona a Bergamo →",
     "Offizielle OMI-Werte nach Zone in Bergamo →"),
    ("Operi anche nei comuni in provincia e nelle valli?",
     "Arbeiten Sie auch in Provinzgemeinden und in den Tälern?"),
    ("Un prezzo sbagliato può costarti mesi sul mercato",
     "Ein falscher Preis kann Sie Monate auf dem Markt kosten"),
    ("Bergamo · Città Alta · Valle Seriana · Provincia",
     "Bergamo · Città Alta · Valle Seriana · Provinz"),
    ("Consulente RE/MAX &middot; Risposta entro 24h",
     "RE/MAX-Berater &middot; Antwort innerhalb von 24h"),
    ("Ultimo passo: dimmi come posso ricontattarti.",
     "Letzter Schritt: sagen Sie mir, wie ich Sie erreichen kann."),
    ("Lavori solo su Bergamo o anche in provincia?",
     "Arbeiten Sie nur in Bergamo oder auch in der Provinz?"),
    ("Agente Immobiliare affiliato RE/MAX Bergamo",
     "RE/MAX-Immobilienberater Bergamo"),
    ("Perch&eacute; non basta una stima online?",
     "Warum reicht eine Online-Schätzung nicht?"),
    ("Le domande che ricevo pi&ugrave; spesso.",
     "Die häufigsten Fragen."),
    ("Treviglio &middot; Provincia di Bergamo",
     "Treviglio &middot; Provinz Bergamo"),
    ("Consulente RE/MAX · Risposta entro 24h",
     "RE/MAX-Berater · Antwort innerhalb von 24h"),
    ("Seriate &middot; Provincia di Bergamo",
     "Seriate &middot; Provinz Bergamo"),
    ("· Bergamo · Città Alta · Provincia",
     "· Bergamo · Città Alta · Provinz"),
    ("Consulta i valori OMI per zona →",
     "OMI-Werte nach Zone →"),
    ("Treviglio · Provincia di Bergamo",
     "Treviglio · Provinz Bergamo"),
    ("Treviglio / Romano di Lombardia",
     "Treviglio / Romano di Lombardia"),
    ("&middot; Scegli il tuo percorso",
     "&middot; Wählen Sie Ihren Weg"),
    ("Seriate · Provincia di Bergamo",
     "Seriate · Provinz Bergamo"),
    ("Zone servite &middot; Bergamo",
     "Betreute Zonen &middot; Bergamo"),
    ("Altra zona provincia Bergamo",
     "Andere Zone Provinz Bergamo"),
    ("Bergamo Citt&agrave; Bassa",
     "Bergamo Citt&agrave; Bassa"),
    ("Centro &middot; Lower Town",
     "Zentrum &middot; Lower Town"),
    ("Dalmine &middot; Treviglio",
     "Dalmine &middot; Treviglio"),
    ("Bergamo Citt&agrave; Alta",
     "Bergamo Citt&agrave; Alta"),
    ("Seriate / Scanzorosciate",
     "Seriate / Scanzorosciate"),
    ("· Scegli il tuo percorso",
     "· Wählen Sie Ihren Weg"),
    ("Richiedi la mia analisi",
     "Meine Analyse anfordern"),
    ("RE/MAX &middot; Bergamo",
     "RE/MAX &middot; Bergamo"),
    ("Zone servite · Bergamo",
     "Betreute Zonen · Bergamo"),
    ("Qualit&agrave; di vita",
     "Lebensqualität"),
    ("Comprare a Bergamo →",
     "In Bergamo kaufen →"),
    ("Bergamo Citt&agrave;",
     "Bergamo Stadt"),
    ("Appartamento Bergamo",
     "Wohnung Bergamo"),
    ("Bergamo Città Bassa",
     "Bergamo Città Bassa"),
    ("Centro · Lower Town",
     "Zentrum · Lower Town"),
    ("Dalmine · Treviglio",
     "Dalmine · Treviglio"),
    ("Numero di telefono",
     "Telefonnummer"),
    ("Superficie &mdash;",
     "Fläche &mdash;"),
    ("Bergamo Città Alta",
     "Bergamo Città Alta"),
    ("Mercato Bergamasco",
     "Markt Bergamasco"),
    ("Attico / Mansarda",
     "Penthouse / Dachgeschoss"),
    ("Citt&agrave; Alta",
     "Citt&agrave; Alta"),
    ("Casa in provincia",
     "Haus in der Provinz"),
    ("Note facoltative",
     "Optionale Anmerkungen"),
    ("Rustico / Casale",
     "Rustico / Bauernhaus"),
    ("RE/MAX · Bergamo",
     "RE/MAX · Bergamo"),
    ("Casa a Treviglio",
     "Haus in Treviglio"),
    ("Qualità di vita",
     "Lebensqualität"),
    ("Nome e Cognome",
     "Vor- und Nachname"),
    ("Dalmine / Osio",
     "Dalmine / Osio"),
    ("Valle Brembana",
     "Valle Brembana"),
    ("Analisi locale",
     "Lokale Analyse"),
    ("Valle Seriana",
     "Valle Seriana"),
    ("Borgo Palazzo",
     "Borgo Palazzo"),
    ("Bergamo Città",
     "Bergamo Stadt"),
    ("Villa / Casa",
     "Villa / Haus"),
    ("Appartamento",
     "Wohnung"),
    ("Superficie —",
     "Fläche —"),
    ("Val Brembana",
     "Val Brembana"),
    ("Provincia BG",
     "Provinz BG"),
    ("Residenziale",
     "Wohnimmobilien"),
    ("Il tuo nome",
     "Ihr Name"),
    ("Val Seriana",
     "Val Seriana"),
    ("Lago d'Iseo",
     "Iseosee"),
    ("Città Alta",
     "Città Alta"),
    ("Espansione",
     "Expansion"),
    ("Colognola",
     "Colognola"),
    ("Continua",
     "Weiter"),
    ("Indietro",
     "Zurück"),
    ("Telefono",
     "Telefon"),
    ("Valli",
     "Täler"),
]

PHRASES_BERGAMO_FR: list[tuple[str, str]] = [
    ("Sono un Agente Immobiliare affiliato RE/MAX con background da geometra e imprenditore. Conosco le specificit&agrave; di ogni zona del territorio bergamasco &mdash; dalla Citt&agrave; Alta al tessuto residenziale della Bassa, dalla Valle Seriana ai comuni di cintura. Ogni micro-mercato ha regole proprie.",
     "Agent immobilier RE/MAX avec un parcours de g&eacute;om&egrave;tre et d'entrepreneur, je connais les sp&eacute;cificit&eacute;s de chaque zone du territoire bergamasque &mdash; de la Citt&agrave; Alta au tissu r&eacute;sidentiel de la Bassa, de la Valle Seriana aux communes de ceinture. Chaque micro-march&eacute; a ses propres r&egrave;gles."),
    ("Dal centro di Bergamo a Citt&agrave; Alta, dalla Valle Seriana alla Bassa, ogni zona ha dinamiche proprie. <strong>Un prezzo sbagliato pu&ograve; costarti mesi sul mercato</strong> o migliaia di euro nella trattativa. Prima della vendita, servono dati reali, metodo e posizionamento corretto.",
     "Du centre de Bergame &agrave; la Citt&agrave; Alta, de la Valle Seriana &agrave; la Bassa, chaque zone a ses dynamiques. <strong>Un mauvais prix peut vous coûter des mois sur le march&eacute;</strong> ou des milliers d'euros en n&eacute;gociation. Avant de vendre, il faut des donn&eacute;es r&eacute;elles, une m&eacute;thode et un positionnement juste."),
    ("Sono un Agente Immobiliare affiliato RE/MAX con background da geometra e imprenditore. Conosco le specificità di ogni zona del territorio bergamasco — dalla Città Alta al tessuto residenziale della Bassa, dalla Valle Seriana ai comuni di cintura. Ogni micro-mercato ha regole proprie.",
     "Agent immobilier RE/MAX avec un parcours de géomètre et d'entrepreneur, je connais les spécificités de chaque zone du territoire bergamasque — de la Città Alta au tissu résidentiel de la Bassa, de la Valle Seriana aux communes de ceinture. Chaque micro-marché a ses propres règles."),
    ("Dal centro di Bergamo a Città Alta, dalla Valle Seriana alla Bassa, ogni zona ha dinamiche proprie. <strong>Un prezzo sbagliato può costarti mesi sul mercato</strong> o migliaia di euro nella trattativa. Prima della vendita, servono dati reali, metodo e posizionamento corretto.",
     "Du centre de Bergame à la Città Alta, de la Valle Seriana à la Bassa, chaque zone a ses dynamiques. <strong>Un mauvais prix peut vous coûter des mois sur le marché</strong> ou des milliers d'euros en négociation. Avant de vendre, il faut des données réelles, une méthode et un positionnement juste."),
    ("Un appartamento in Citt&agrave; Alta non segue le stesse dinamiche di un trilocale in Citt&agrave; Bassa, di una casa in Valle Seriana o di un immobile nei comuni di cintura verso Milano. Per questo ogni analisi deve essere costruita sulla zona reale dell'immobile.",
     "Un appartement en Citt&agrave; Alta ne suit pas les mêmes dynamiques qu'un trois-pi&egrave;ces en Citt&agrave; Bassa, une maison en Valle Seriana ou un bien dans les communes de ceinture vers Milan. Chaque analyse doit donc être construite sur la zone r&eacute;elle du bien."),
    ("Le stime automatiche non vedono stato interno, piano, affaccio, criticit&agrave; documentali e domanda reale della zona. A Bergamo la differenza tra Citt&agrave; Alta e Citt&agrave; Bassa, o tra i vari quartieri, pu&ograve; incidere significativamente sul valore.",
     "Les estimations automatiques ne voient ni l'&eacute;tat int&eacute;rieur, ni l'&eacute;tage, ni l'exposition, ni les risques documentaires, ni la demande r&eacute;elle de la zone. &Agrave; Bergame, l'&eacute;cart entre Citt&agrave; Alta et Citt&agrave; Bassa, ou entre les quartiers, peut peser significativement sur la valeur."),
    ("Un appartamento in Città Alta non segue le stesse dinamiche di un trilocale in Città Bassa, di una casa in Valle Seriana o di un immobile nei comuni di cintura verso Milano. Per questo ogni analisi deve essere costruita sulla zona reale dell'immobile.",
     "Un appartement en Città Alta ne suit pas les mêmes dynamiques qu'un trois-pièces en Città Bassa, une maison en Valle Seriana ou un bien dans les communes de ceinture vers Milan. Chaque analyse doit donc être construite sur la zone réelle du bien."),
    ("La mia consulenza rimane personale e diretta. L'affiliazione RE/MAX aggiunge autorit&agrave;, rete e maggiore visibilit&agrave; &mdash; anche per acquirenti che si spostano da Milano verso Bergamo e per chi cerca soluzioni sul Lago d'Iseo bergamasco.",
     "Mon conseil reste personnel et direct. L'affiliation RE/MAX apporte autorit&eacute;, r&eacute;seau et visibilit&eacute; accrue &mdash; y compris pour les acheteurs qui s'installent de Milan vers Bergame et pour ceux qui cherchent sur le lac d'Iseo bergamasque."),
    ("agente immobiliare Bergamo, agente RE/MAX Bergamo, valutazione casa Bergamo, vendere casa Bergamo, agente immobiliare Citt&agrave; Alta, agente immobiliare provincia Bergamo, valutazione immobile Bergamo, Maurizio Piraino immobiliare Bergamo",
     "agent immobilier Bergame, agent RE/MAX Bergame, estimation immobili&egrave;re Bergame, vendre maison Bergame, agent immobilier Citt&agrave; Alta, agent immobilier province Bergame, estimation bien Bergame, Maurizio Piraino immobilier Bergame"),
    ("Dovevo gestire la vendita di una casa in provincia ereditata. Il background tecnico da geometra ha individuato subito una difformit&agrave; catastale che avrebbe bloccato il rogito. Risolta prima delle visite, vendita conclusa regolarmente.",
     "Je devais g&eacute;rer la vente d'une maison h&eacute;rit&eacute;e en province. Le background technique de g&eacute;om&egrave;tre a identifi&eacute; imm&eacute;diatement une difformit&eacute; cadastrale qui aurait bloqu&eacute; l'acte. R&eacute;solue avant les visites, vente conclue r&eacute;guli&egrave;rement."),
    ("Le stime automatiche non vedono stato interno, piano, affaccio, criticità documentali e domanda reale della zona. A Bergamo la differenza tra Città Alta e Città Bassa, o tra i vari quartieri, può incidere significativamente sul valore.",
     "Les estimations automatiques ne voient ni l'état intérieur, ni l'étage, ni l'exposition, ni les risques documentaires, ni la demande réelle de la zone. À Bergame, l'écart entre Città Alta et Città Bassa, ou entre les quartiers, peut peser significativement sur la valeur."),
    ("agente immobiliare Bergamo, agente RE/MAX Bergamo, valutazione casa Bergamo, vendere casa Bergamo, agente immobiliare Città Alta, agente immobiliare provincia Bergamo, valutazione immobile Bergamo, Maurizio Piraino immobiliare Bergamo",
     "agent immobilier Bergame, agent RE/MAX Bergame, estimation immobilière Bergame, vendre maison Bergame, agent immobilier Città Alta, agent immobilier province Bergame, estimation bien Bergame, Maurizio Piraino immobilier Bergame"),
    ("Dovevo gestire la vendita di una casa in provincia ereditata. Il background tecnico da geometra ha individuato subito una difformità catastale che avrebbe bloccato il rogito. Risolta prima delle visite, vendita conclusa regolarmente.",
     "Je devais gérer la vente d'une maison héritée en province. Le background technique de géomètre a identifié immédiatement une difformité cadastrale qui aurait bloqué l'acte. Résolue avant les visites, vente conclue régulièrement."),
    ("La mia consulenza rimane personale e diretta. L'affiliazione RE/MAX aggiunge autorità, rete e maggiore visibilità — anche per acquirenti che si spostano da Milano verso Bergamo e per chi cerca soluzioni sul Lago d'Iseo bergamasco.",
     "Mon conseil reste personnel et direct. L'affiliation RE/MAX apporte autorité, réseau et visibilité accrue — y compris pour les acheteurs qui s'installent de Milan vers Bergame et pour ceux qui cherchent sur le lac d'Iseo bergamasque."),
    ("Avevo provato a vendere il mio appartamento da solo per quasi sei mesi senza risultati concreti. L'analisi del micro-mercato della mia zona e il posizionamento corretto del prezzo hanno cambiato tutto. Chiuso in poche settimane.",
     "J'avais tenté de vendre mon appartement seul pendant près de six mois sans résultat concret. L'analyse du micro-marché de ma zone et le bon positionnement du prix ont tout changé. Conclu en quelques semaines."),
    ("La mia casa a Treviglio era sul mercato da mesi. Il problema non era l'immobile, ma il posizionamento sbagliato per quella zona. Con la strategia giusta e gli acquirenti profilati correttamente, abbiamo chiuso in tempi brevi.",
     "Ma maison à Treviglio était sur le marché depuis des mois. Le problème n'était pas le bien, mais un mauvais positionnement pour cette zone. Avec la bonne stratégie et des acheteurs correctement profilés, nous avons conclu rapidement."),
    ("La maggior parte degli agenti tratta tutto allo stesso modo. Io costruisco una strategia su misura per la zona specifica &mdash; Bergamo centro, collina, provincia &mdash; prima ancora di pubblicare la prima foto.",
     "La plupart des agents traitent tout de la même façon. Je construis une strat&eacute;gie sur mesure pour la zone sp&eacute;cifique &mdash; Bergame centre, colline, province &mdash; avant même de publier la premi&egrave;re photo."),
    ("Vuoi capire su quali dati si basa il prezzo e distinguere una stima seria da una promessa &mdash; specialmente quando le valutazioni variano tra Citt&agrave; Alta, la Citt&agrave; Bassa e i comuni in provincia.",
     "Vous voulez comprendre sur quelles donn&eacute;es repose le prix et distinguer une estimation s&eacute;rieuse d'une promesse &mdash; surtout quand les &eacute;valuations varient entre Citt&agrave; Alta, Citt&agrave; Bassa et les communes de province."),
    ("Mesi online, poche visite, offerte basse: spesso il problema non &egrave; la casa, ma il posizionamento sbagliato per quella zona &mdash; che a Bergamo cambia significativamente tra centro, collina e pianura.",
     "Des mois en ligne, peu de visites, offres basses : souvent le probl&egrave;me n'est pas la maison, mais un mauvais positionnement pour cette zone &mdash; qui &agrave; Bergame varie nettement entre centre, colline et plaine."),
    ("La maggior parte degli agenti tratta tutto allo stesso modo. Io costruisco una strategia su misura per la zona specifica — Bergamo centro, collina, provincia — prima ancora di pubblicare la prima foto.",
     "La plupart des agents traitent tout de la même façon. Je construis une stratégie sur mesure pour la zone spécifique — Bergame centre, colline, province — avant même de publier la première photo."),
    ("S&igrave;. Opero su tutto il territorio bergamasco &mdash; Bergamo citt&agrave;, Citt&agrave; Alta, Valle Seriana, Valle Brembana, comuni di cintura e Bassa bergamasca. Ogni zona ha dinamiche proprie.",
     "Oui. J'op&egrave;re sur tout le territoire bergamasque &mdash; Bergame ville, Citt&agrave; Alta, Valle Seriana, Valle Brembana, communes de ceinture et Bassa bergamasca. Chaque zone a ses dynamiques propres."),
    ("Mesi online, poche visite, offerte basse: spesso il problema non è la casa, ma il posizionamento sbagliato per quella zona — che a Bergamo cambia significativamente tra centro, collina e pianura.",
     "Des mois en ligne, peu de visites, offres basses : souvent le problème n'est pas la maison, mais un mauvais positionnement pour cette zone — qui à Bergame varie nettement entre centre, colline et plaine."),
    ("Vuoi capire su quali dati si basa il prezzo e distinguere una stima seria da una promessa — specialmente quando le valutazioni variano tra Città Alta, la Città Bassa e i comuni in provincia.",
     "Vous voulez comprendre sur quelles données repose le prix et distinguer une estimation sérieuse d'une promesse — surtout quand les évaluations varient entre Città Alta, Città Bassa et les communes de province."),
    ("S&igrave;. Sapere oggi quanto vale il tuo immobile ti permette di pianificare senza pressione, scegliere il momento migliore e non farti trovare impreparato quando decidi di procedere.",
     "Oui. Connaître aujourd'hui la valeur de votre bien vous permet de planifier sans pression, de choisir le meilleur moment et de ne pas être pris de court quand vous d&eacute;cidez d'agir."),
    ("Dalla prima analisi alla possibile strategia di vendita: ogni fase &egrave; chiara, definita e concordata con te &mdash; ovunque si trovi il tuo immobile nel territorio bergamasco.",
     "De la premi&egrave;re analyse &agrave; la strat&eacute;gie de vente possible : chaque phase est claire, d&eacute;finie et convenue avec vous &mdash; o&ugrave; que se trouve votre bien sur le territoire bergamasque."),
    ("Opero su Bergamo citt&agrave; e provincia e, tramite RE/MAX, posso coordinarmi anche con colleghi nelle altre province lombarde se il tuo immobile o il tuo obiettivo lo richiede.",
     "J'op&egrave;re sur Bergame ville et province et, via RE/MAX, je peux aussi me coordonner avec des coll&egrave;gues dans les autres provinces lombardes si votre bien ou votre objectif l'exige."),
    ("Ti mostro il mercato reale della tua zona, le criticit&agrave; dell'immobile e la strategia pi&ugrave; adatta per Bergamo e provincia &mdash; prima ancora di parlare di incarico.",
     "Je vous montre le march&eacute; r&eacute;el de votre zone, les points faibles du bien et la strat&eacute;gie la plus adapt&eacute;e pour Bergame et province &mdash; avant même de parler de mandat."),
    ("Sì. Sapere oggi quanto vale il tuo immobile ti permette di pianificare senza pressione, scegliere il momento migliore e non farti trovare impreparato quando decidi di procedere.",
     "Oui. Connaître aujourd'hui la valeur de votre bien vous permet de planifier sans pression, de choisir le meilleur moment et de ne pas être pris de court quand vous décidez d'agir."),
    ("&quot;A Bergamo, Citt&agrave; Alta e la Citt&agrave; Bassa sono due mercati diversi. Conoscere questa differenza prima del lancio vale migliaia di euro sulla trattativa.&quot;",
     "&quot;&Agrave; Bergame, la Citt&agrave; Alta et la Citt&agrave; Bassa sont deux march&eacute;s diff&eacute;rents. Connaître cette diff&eacute;rence avant le lancement vaut des milliers d'euros en n&eacute;gociation.&quot;"),
    ("Sì. Opero su tutto il territorio bergamasco — Bergamo città, Città Alta, Valle Seriana, Valle Brembana, comuni di cintura e Bassa bergamasca. Ogni zona ha dinamiche proprie.",
     "Oui. J'opère sur tout le territoire bergamasque — Bergame ville, Città Alta, Valle Seriana, Valle Brembana, communes de ceinture et Bassa bergamasca. Chaque zone a ses dynamiques propres."),
    ("Opero su Bergamo città e provincia e, tramite RE/MAX, posso coordinarmi anche con colleghi nelle altre province lombarde se il tuo immobile o il tuo obiettivo lo richiede.",
     "J'opère sur Bergame ville et province et, via RE/MAX, je peux aussi me coordonner avec des collègues dans les autres provinces lombardes si votre bien ou votre objectif l'exige."),
    ("Agente Immobiliare affiliato RE/MAX &middot; REA BS-639579 &middot; P.IVA 14597560961 &middot; Bergamo &middot; Citt&agrave; Alta &middot; Valle Seriana &middot; Provincia",
     "Agent immobilier RE/MAX &middot; REA BS-639579 &middot; P.IVA 14597560961 &middot; Bergame &middot; Citt&agrave; Alta &middot; Valle Seriana &middot; Province"),
    ("Dalla prima analisi alla possibile strategia di vendita: ogni fase è chiara, definita e concordata con te — ovunque si trovi il tuo immobile nel territorio bergamasco.",
     "De la première analyse à la stratégie de vente possible : chaque phase est claire, définie et convenue avec vous — où que se trouve votre bien sur le territoire bergamasque."),
    ("Ogni vendita ha criticit&agrave; diverse. Il primo passo &egrave; capire cosa pu&ograve; rallentare, svalutare o valorizzare il tuo immobile nel territorio bergamasco.",
     "Chaque vente a des enjeux diff&eacute;rents. La premi&egrave;re &eacute;tape : comprendre ce qui peut ralentir, d&eacute;valoriser ou valoriser votre bien sur le territoire bergamasque."),
    ("Ti mostro il mercato reale della tua zona, le criticità dell'immobile e la strategia più adatta per Bergamo e provincia — prima ancora di parlare di incarico.",
     "Je vous montre le marché réel de votre zone, les points faibles du bien et la stratégie la plus adaptée pour Bergame et province — avant même de parler de mandat."),
    ("Un marchio riconoscibile rassicura i proprietari e gli acquirenti &mdash; anche da fuori provincia e da acquirenti che si spostano da Milano verso Bergamo.",
     "Une marque reconnaissable rassure propri&eacute;taires et acheteurs &mdash; y compris de l'ext&eacute;rieur de la province et ceux qui s'installent de Milan vers Bergame."),
    ("\"A Bergamo, Città Alta e la Città Bassa sono due mercati diversi. Conoscere questa differenza prima del lancio vale migliaia di euro sulla trattativa.\"",
     "&quot;À Bergame, la Città Alta et la Città Bassa sont deux marchés différents. Connaître cette différence avant le lancement vaut des milliers d'euros en négociation.&quot;"),
    ("Vuoi vendere casa a Bergamo, in Citt&agrave; Alta o in provincia? Ricevi un'analisi immobiliare riservata basata su dati reali e strategia di vendita.",
     "Vous souhaitez vendre &agrave; Bergame, en Citt&agrave; Alta ou en province ? Recevez une analyse immobili&egrave;re confidentielle bas&eacute;e sur des donn&eacute;es r&eacute;elles et une strat&eacute;gie de vente."),
    ("Un marchio riconoscibile rassicura i proprietari e gli acquirenti — anche da fuori provincia e da acquirenti che si spostano da Milano verso Bergamo.",
     "Une marque reconnaissable rassure propriétaires et acheteurs — y compris de l'extérieur de la province et ceux qui s'installent de Milan vers Bergame."),
    ("La collaborazione tra professionisti amplia le possibilit&agrave; di intercettare acquirenti qualificati, anche dal milanese e da fuori provincia.",
     "La collaboration entre professionnels &eacute;largit les possibilit&eacute;s d'intercepter des acheteurs qualifi&eacute;s, y compris depuis Milan et hors province."),
    ("Ogni vendita ha criticità diverse. Il primo passo è capire cosa può rallentare, svalutare o valorizzare il tuo immobile nel territorio bergamasco.",
     "Chaque vente a des enjeux différents. La première étape : comprendre ce qui peut ralentir, dévaloriser ou valoriser votre bien sur le territoire bergamasque."),
    ("Comuni come Dalmine, Seriate e Treviglio attraggono chi cerca pi&ugrave; spazio rispetto a Milano o Bergamo, con ottimi collegamenti ferroviari.",
     "Des communes comme Dalmine, Seriate et Treviglio attirent ceux qui cherchent plus d'espace qu'&agrave; Milan ou Bergame, avec d'excellentes liaisons ferroviaires."),
    ("Vuoi vendere casa a Bergamo, in Città Alta o in provincia? Ricevi un'analisi immobiliare riservata basata su dati reali e strategia di vendita.",
     "Vous souhaitez vendre à Bergame, en Città Alta ou en province ? Recevez une analyse immobilière confidentielle basée sur des données réelles et une stratégie de vente."),
    ("Definiamo prezzo, timing, comunicazione e profilo dell'acquirente pi&ugrave; adatto alla tua zona specifica &mdash; Bergamo, valli o provincia.",
     "Nous d&eacute;finissons prix, timing, communication et profil d'acheteur le plus adapt&eacute; &agrave; votre zone sp&eacute;cifique &mdash; Bergame, vall&eacute;es ou province."),
    ("Domanda solida, con forte interesse da acquirenti milanesi. Citt&agrave; Alta e Citt&agrave; Bassa hanno dinamiche di prezzo molto differenti.",
     "Demande solide, avec un fort int&eacute;rêt d'acheteurs milanais. Citt&agrave; Alta et Citt&agrave; Bassa ont des dynamiques de prix tr&egrave;s diff&eacute;rentes."),
    ("La collaborazione tra professionisti amplia le possibilità di intercettare acquirenti qualificati, anche dal milanese e da fuori provincia.",
     "La collaboration entre professionnels élargit les possibilités d'intercepter des acheteurs qualifiés, y compris depuis Milan et hors province."),
    ("Comuni come Dalmine, Seriate e Treviglio attraggono chi cerca più spazio rispetto a Milano o Bergamo, con ottimi collegamenti ferroviari.",
     "Des communes comme Dalmine, Seriate et Treviglio attirent ceux qui cherchent plus d'espace qu'à Milan ou Bergame, avec d'excellentes liaisons ferroviaires."),
    ("Valle Seriana e Valle Brembana attraggono chi cerca qualit&agrave; di vita, verde e prezzi pi&ugrave; accessibili rispetto al capoluogo.",
     "Valle Seriana et Valle Brembana attirent ceux qui recherchent qualit&eacute; de vie, verdure et prix plus accessibles que dans le chef-lieu."),
    ("Vendere casa a Bergamo, in Citt&agrave; Alta o in provincia? Analisi immobiliare riservata su dati reali, prima di parlare di incarico.",
     "Vendre &agrave; Bergame, en Citt&agrave; Alta ou en province ? Analyse immobili&egrave;re confidentielle sur donn&eacute;es r&eacute;elles, avant tout mandat."),
    ("Prima di decidere, vuoi leggere il mercato reale della tua zona &mdash; Bergamo, valle o provincia &mdash; e non muoverti a sensazione.",
     "Avant de d&eacute;cider, vous voulez lire le march&eacute; r&eacute;el de votre zone &mdash; Bergame, vall&eacute;e ou province &mdash; et ne pas agir au feeling."),
    ("Confronti zona per zona &mdash; Citt&agrave; Alta, Citt&agrave; Bassa, valli, pianura &mdash; e posizionamento corretto del prezzo.",
     "Comparaisons zone par zone &mdash; Citt&agrave; Alta, Citt&agrave; Bassa, vall&eacute;es, plaine &mdash; et positionnement prix correct."),
    ("Definiamo prezzo, timing, comunicazione e profilo dell'acquirente più adatto alla tua zona specifica — Bergamo, valli o provincia.",
     "Nous définissons prix, timing, communication et profil d'acheteur le plus adapté à votre zone spécifique — Bergame, vallées ou province."),
    ("Vendere casa a Bergamo, in Città Alta o in provincia? Analisi immobiliare riservata su dati reali, prima di parlare di incarico.",
     "Vendre à Bergame, en Città Alta ou en province ? Analyse immobilière confidentielle sur données réelles, avant tout mandat."),
    ("Domanda solida, con forte interesse da acquirenti milanesi. Città Alta e Città Bassa hanno dinamiche di prezzo molto differenti.",
     "Demande solide, avec un fort intérêt d'acheteurs milanais. Città Alta et Città Bassa ont des dynamiques de prix très différentes."),
    ("&Egrave; un confronto strutturato sul tuo immobile, sulla micro-zona e sulla strategia di vendita pi&ugrave; adatta a Bergamo.",
     "C'est une comparaison structur&eacute;e de votre bien, de la micro-zone et de la strat&eacute;gie de vente la plus adapt&eacute;e &agrave; Bergame."),
    ("Prima di firmare qualsiasi cosa, vuoi una strategia chiara, riservata e costruita sulla realt&agrave; del mercato bergamasco.",
     "Avant de signer quoi que ce soit, vous voulez une strat&eacute;gie claire, confidentielle et fond&eacute;e sur la r&eacute;alit&eacute; du march&eacute; bergamasque."),
    ("Prima di decidere, vuoi leggere il mercato reale della tua zona — Bergamo, valle o provincia — e non muoverti a sensazione.",
     "Avant de décider, vous voulez lire le marché réel de votre zone — Bergame, vallée ou province — et ne pas agir au feeling."),
    ("Valle Seriana e Valle Brembana attraggono chi cerca qualità di vita, verde e prezzi più accessibili rispetto al capoluogo.",
     "Valle Seriana et Valle Brembana attirent ceux qui recherchent qualité de vie, verdure et prix plus accessibles que dans le chef-lieu."),
    ("Leggo l'immobile, la zona specifica e ti mostro dati, criticit&agrave; e potenzialit&agrave; prima di parlare di incarico.",
     "J'analyse le bien, la zone sp&eacute;cifique, et vous montre donn&eacute;es, points faibles et potentiel &mdash; avant de parler de mandat."),
    ("Agente Immobiliare affiliato RE/MAX · REA BS-639579 · P.IVA 14597560961 · Bergamo · Città Alta · Valle Seriana · Provincia",
     "Agent immobilier RE/MAX · REA BS-639579 · P.IVA 14597560961 · Bergame · Città Alta · Valle Seriana · Province"),
    ("Prima di firmare qualsiasi cosa, vuoi una strategia chiara, riservata e costruita sulla realtà del mercato bergamasco.",
     "Avant de signer quoi que ce soit, vous voulez une stratégie claire, confidentielle et fondée sur la réalité du marché bergamasque."),
    ("Bergamo Alta, Borgo Palazzo, Val Seriana e i comuni della provincia hanno dinamiche di prezzo molto diverse tra loro.",
     "Bergamo Alta, Borgo Palazzo, Val Seriana et les communes de province ont des dynamiques de prix très différentes."),
    ("La differenza resta nel modo in cui l'immobile viene analizzato, posizionato e presentato per la sua zona specifica.",
     "La différence réside dans la façon dont le bien est analysé, positionné et présenté pour sa zone spécifique."),
    ("È un confronto strutturato sul tuo immobile, sulla micro-zona e sulla strategia di vendita più adatta a Bergamo.",
     "C'est une comparaison structurée de votre bien, de la micro-zone et de la stratégie de vente la plus adaptée à Bergame."),
    ("Leggo l'immobile, la zona specifica e ti mostro dati, criticità e potenzialità prima di parlare di incarico.",
     "J'analyse le bien, la zone spécifique, et vous montre données, points faibles et potentiel — avant de parler de mandat."),
    ("Confronti zona per zona — Città Alta, Città Bassa, valli, pianura — e posizionamento corretto del prezzo.",
     "Comparaisons zone par zone — Città Alta, Città Bassa, vallées, plaine — et positionnement prix correct."),
    ("Se decidi di procedere, ti accompagno in visite, offerte, trattativa e passaggi tecnici fino al rogito.",
     "Si vous décidez de poursuivre, je vous accompagne en visites, offres, négociation et démarches techniques jusqu'à l'acte notarié."),
    ("Agente Immobiliare affiliato RE/MAX &middot; Bergamo &middot; Citt&agrave; Alta &middot; Provincia",
     "Agent immobilier RE/MAX &middot; Bergame &middot; Citt&agrave; Alta &middot; Province"),
    ("Prima casa, seconda casa, investimento: ogni profilo richiede comunicazione e target differenti.",
     "Première maison, résidence secondaire, investissement : chaque profil exige une communication et une cible différentes."),
    ("Agente Immobiliare affiliato RE/MAX. Consulenza per venditori e acquirenti in Lombardia.",
     "Agent immobilier RE/MAX. Conseil pour vendeurs et acheteurs en Lombardie."),
    ("Analisi immobiliare riservata per vendere casa a Bergamo, Citt&agrave; Alta e provincia.",
     "Analyse immobili&egrave;re confidentielle pour vendre &agrave; Bergame, Citt&agrave; Alta et province."),
    ("Dalla prima visita alla firma dal notaio, senza improvvisazione e senza lasciarti solo.",
     "De la première visite à l'acte notarié, sans improvisation et sans vous laisser seul."),
    ("Analisi immobiliare riservata per vendere casa a Bergamo, Città Alta e provincia.",
     "Analyse immobilière confidentielle pour vendre à Bergame, Città Alta et province."),
    ("Prima di vendere casa a Bergamo o in provincia, serve capire davvero quanto vale.",
     "Avant de vendre à Bergame ou en province, il faut connaître la vraie valeur de votre bien."),
    ("Valutazione riservata su Bergamo, valli e provincia. Nessun obbligo di incarico.",
     "Évaluation confidentielle sur Bergame, vallées et province. Aucune obligation de mandat."),
    ("A Bergamo e provincia, vendere bene non &egrave; fortuna. &Egrave; strategia.",
     "&Agrave; Bergame et en province, bien vendre n'est pas une question de chance &mdash; c'est une strat&eacute;gie."),
    ("Bergamo &middot; Citt&agrave; Alta &middot; Valle Seriana &middot; Provincia",
     "Bergame &middot; Citt&agrave; Alta &middot; Valle Seriana &middot; Province"),
    ("Comprare a Bergamo senza pagare troppo. Analisi OMI e verifica tecnica.",
     "Acheter à Bergame sans payer trop cher. Analyse OMI et vérification technique."),
    ("Agente Immobiliare affiliato RE/MAX · Bergamo · Città Alta · Provincia",
     "Agent immobilier RE/MAX · Bergame · Città Alta · Province"),
    ("Scrivi zona o comune (es. Citt&agrave; Alta, Seriate, Treviglio...)",
     "Indiquez zone ou commune (ex. Citt&agrave; Alta, Seriate, Treviglio …)"),
    ("Agente Immobiliare affiliato RE/MAX &middot; Bergamo e Provincia",
     "Agent immobilier RE/MAX &middot; Bergame et Province"),
    ("Agente Immobiliare Bergamo | Valutazione Casa &middot; Piraino",
     "Agent immobilier Bergame | Estimation immobili&egrave;re &middot; Piraino"),
    ("Agente Immobiliare affiliato RE/MAX Bergamo | Valutazione Casa",
     "Agent immobilier RE/MAX Bergame | Estimation immobilière"),
    ("&middot; Bergamo &middot; Citt&agrave; Alta &middot; Provincia",
     "&middot; Bergame &middot; Citt&agrave; Alta &middot; Province"),
    ("Scrivi zona o comune (es. Città Alta, Seriate, Treviglio...)",
     "Indiquez zone ou commune (ex. Città Alta, Seriate, Treviglio …)"),
    ("Bergamo cambia zona per zona. Ogni mercato ha le sue regole.",
     "Bergame change de zone en zone. Chaque marché a ses propres règles."),
    ("Maurizio Piraino Agente Immobiliare affiliato RE/MAX Bergamo",
     "Maurizio Piraino agent immobilier RE/MAX Bergame"),
    ("Agente Immobiliare affiliato RE/MAX · Bergamo e Provincia",
     "Agent immobilier RE/MAX · Bergame et Province"),
    ("Un prezzo sbagliato pu&ograve; costarti mesi sul mercato",
     "Un mauvais prix peut vous coûter des mois sur le march&eacute;"),
    ("Agente Immobiliare Bergamo | Valutazione Casa · Piraino",
     "Agent immobilier Bergame | Estimation immobilière · Piraino"),
    ("Consulta i valori OMI ufficiali per zona a Bergamo →",
     "Consultez les valeurs OMI officielles par zone à Bergame →"),
    ("Operi anche nei comuni in provincia e nelle valli?",
     "Intervenez-vous aussi dans les communes de province et les vallées ?"),
    ("Un prezzo sbagliato può costarti mesi sul mercato",
     "Un mauvais prix peut vous coûter des mois sur le marché"),
    ("Bergamo · Città Alta · Valle Seriana · Provincia",
     "Bergame · Città Alta · Valle Seriana · Province"),
    ("Consulente RE/MAX &middot; Risposta entro 24h",
     "Consultant RE/MAX &middot; R&eacute;ponse sous 24h"),
    ("Ultimo passo: dimmi come posso ricontattarti.",
     "Dernière étape : dites-moi comment vous recontacter."),
    ("Lavori solo su Bergamo o anche in provincia?",
     "Travaillez-vous uniquement sur Bergame ou aussi en province ?"),
    ("Agente Immobiliare affiliato RE/MAX Bergamo",
     "Agent immobilier RE/MAX Bergame"),
    ("Perch&eacute; non basta una stima online?",
     "Pourquoi une estimation en ligne ne suffit-elle pas ?"),
    ("Le domande che ricevo pi&ugrave; spesso.",
     "Les questions les plus fr&eacute;quentes."),
    ("Treviglio &middot; Provincia di Bergamo",
     "Treviglio &middot; Province de Bergame"),
    ("Consulente RE/MAX · Risposta entro 24h",
     "Consultant RE/MAX · Réponse sous 24h"),
    ("Seriate &middot; Provincia di Bergamo",
     "Seriate &middot; Province de Bergame"),
    ("· Bergamo · Città Alta · Provincia",
     "· Bergame · Città Alta · Province"),
    ("Consulta i valori OMI per zona →",
     "Consultez les valeurs OMI par zone →"),
    ("Treviglio · Provincia di Bergamo",
     "Treviglio · Province de Bergame"),
    ("Treviglio / Romano di Lombardia",
     "Treviglio / Romano di Lombardia"),
    ("&middot; Scegli il tuo percorso",
     "&middot; Choisissez votre parcours"),
    ("Seriate · Provincia di Bergamo",
     "Seriate · Province de Bergame"),
    ("Zone servite &middot; Bergamo",
     "Zones couvertes &middot; Bergame"),
    ("Altra zona provincia Bergamo",
     "Autre zone province Bergame"),
    ("Bergamo Citt&agrave; Bassa",
     "Bergame Citt&agrave; Bassa"),
    ("Centro &middot; Lower Town",
     "Centre &middot; Lower Town"),
    ("Dalmine &middot; Treviglio",
     "Dalmine &middot; Treviglio"),
    ("Bergamo Citt&agrave; Alta",
     "Bergame Citt&agrave; Alta"),
    ("Seriate / Scanzorosciate",
     "Seriate / Scanzorosciate"),
    ("· Scegli il tuo percorso",
     "· Choisissez votre parcours"),
    ("Richiedi la mia analisi",
     "Demander mon analyse"),
    ("RE/MAX &middot; Bergamo",
     "RE/MAX &middot; Bergame"),
    ("Zone servite · Bergamo",
     "Zones couvertes · Bergame"),
    ("Qualit&agrave; di vita",
     "Qualit&eacute; de vie"),
    ("Comprare a Bergamo →",
     "Acheter à Bergame →"),
    ("Bergamo Citt&agrave;",
     "Bergame ville"),
    ("Appartamento Bergamo",
     "Appartement Bergame"),
    ("Bergamo Città Bassa",
     "Bergame Città Bassa"),
    ("Centro · Lower Town",
     "Centre · Lower Town"),
    ("Dalmine · Treviglio",
     "Dalmine · Treviglio"),
    ("Numero di telefono",
     "Numéro de téléphone"),
    ("Superficie &mdash;",
     "Surface &mdash;"),
    ("Bergamo Città Alta",
     "Bergame Città Alta"),
    ("Mercato Bergamasco",
     "Marché Bergamasque"),
    ("Attico / Mansarda",
     "Attique / Mansarde"),
    ("Citt&agrave; Alta",
     "Citt&agrave; Alta"),
    ("Casa in provincia",
     "Maison en province"),
    ("Note facoltative",
     "Notes facultatives"),
    ("Rustico / Casale",
     "Rustique / Corpo di fattoria"),
    ("RE/MAX · Bergamo",
     "RE/MAX · Bergame"),
    ("Casa a Treviglio",
     "Maison à Treviglio"),
    ("Qualità di vita",
     "Qualité de vie"),
    ("Nome e Cognome",
     "Nom et prénom"),
    ("Dalmine / Osio",
     "Dalmine / Osio"),
    ("Valle Brembana",
     "Valle Brembana"),
    ("Analisi locale",
     "Analyse locale"),
    ("Valle Seriana",
     "Valle Seriana"),
    ("Borgo Palazzo",
     "Borgo Palazzo"),
    ("Bergamo Città",
     "Bergame ville"),
    ("Villa / Casa",
     "Villa / Maison"),
    ("Appartamento",
     "Appartement"),
    ("Superficie —",
     "Surface —"),
    ("Val Brembana",
     "Val Brembana"),
    ("Provincia BG",
     "Province BG"),
    ("Residenziale",
     "Résidentiel"),
    ("Il tuo nome",
     "Votre nom"),
    ("Val Seriana",
     "Val Seriana"),
    ("Lago d'Iseo",
     "Lac d'Iseo"),
    ("Città Alta",
     "Città Alta"),
    ("Espansione",
     "Expansion"),
    ("Colognola",
     "Colognola"),
    ("Continua",
     "Continuer"),
    ("Indietro",
     "Retour"),
    ("Telefono",
     "Téléphone"),
    ("Valli",
     "Vallées"),
]
