"""Province-specific seller copy for pages cloned from Bergamo template."""

from __future__ import annotations

SELLER_LOCALIZE: dict[str, dict[str, str | list]] = {
    "como": {
        "portrait_span": "RE/MAX &middot; Como e Lago di Como",
        "about_lead": "Conosco le dinamiche di Como citt&agrave;, del Lago di Como e della Brianza comense. Ogni micro-zona ha regole proprie su prezzo, tempi e tipo di acquirente.",
        "quote": "&quot;Sul Lago di Como due ville a pochi minuti possono valere cifre molto diverse. La micro-zona decide &mdash; non la vista da cartolina.&quot;",
        "strategy": "Costruisco una strategia su misura per Como centro, lago o Brianza &mdash; prima ancora di pubblicare la prima foto.",
        "method_1_p": "Confronti tra centro storico, riviera e comuni di cintura &mdash; con posizionamento corretto del prezzo.",
        "network_p": "L'affiliazione RE/MAX aggiunge autorit&agrave;, rete e visibilit&agrave; &mdash; anche per acquirenti che arrivano da Milano o dall'estero sul lago.",
        "network_1_p": "Un marchio riconoscibile rassicura proprietari e acquirenti sul lago e in Brianza.",
        "market_kicker": "Mercato Comasco",
        "market_h2": "Como e il lago cambiano comune per comune.",
        "market_intro": "Un appartamento in centro storico non segue le stesse dinamiche di Cernobbio, Cant&ugrave; o dei borghi sul lago. Ogni analisi deve partire dalla micro-zona reale.",
        "market_1_span": "Lago di Como",
        "market_1_h": "Fronte lago",
        "market_1_p": "Mercato premium con domanda locale e internazionale: i prezzi cambiano rapidamente da un comune all'altro.",
        "market_2_span": "Como citt&agrave;",
        "market_2_h": "Centro e quartieri",
        "market_2_p": "Domanda residenziale solida, forte interesse da chi lavora tra Como e Milano.",
        "market_3_span": "Brianza comense",
        "market_3_h": "Cant&ugrave; e cintura",
        "market_3_p": "Pi&ugrave; spazio e collegamenti verso Milano, ma con dinamiche di prezzo proprie.",
        "testimonials": [
            ("LC", "Appartamento Como", "Como centro", "Avevo tre valutazioni molto diverse. L'analisi della micro-zona mi ha aiutato a capire il posizionamento giusto prima di uscire sul mercato."),
            ("MR", "Villa sul lago", "Cernobbio", "Sul lago &egrave; facile sbagliare prezzo per emozione. Confronto OMI e strategia mirata: vendita conclusa senza mesi di attesa."),
            ("SF", "Trilocale Brianza", "Cant&ugrave;", "Prima della pubblicazione abbiamo sistemato criticit&agrave; documentali. Le visite sono state pi&ugrave; serene e la trattativa pi&ugrave; veloce."),
        ],
        "final_h2": "Prima di vendere a Como o sul lago, serve capire davvero quanto vale.",
        "final_p": "Ti mostro il mercato reale della tua zona, le criticit&agrave; dell'immobile e la strategia pi&ugrave; adatta &mdash; prima ancora di parlare di incarico.",
    },
    "varese": {
        "portrait_span": "RE/MAX &middot; Varese e Provincia",
        "about_lead": "Seguo il mercato varesino, l'Altomilanese e le zone prealpine. Chi esce da Milano cerca spazio, ma ogni comune ha la sua curva di prezzo.",
        "quote": "&quot;Tra Varese, Busto e i comuni prealpini, lo stesso trilocale pu&ograve; cambiare valore in modo netto. La micro-zona va letta prima del lancio.&quot;",
        "strategy": "Costruisco una strategia su misura per Varese citt&agrave;, Altomilanese o zona laghi &mdash; prima ancora di pubblicare la prima foto.",
        "method_1_p": "Confronti tra Varese, Busto Arsizio, Gallarate e comuni prealpini &mdash; con posizionamento corretto del prezzo.",
        "network_p": "L'affiliazione RE/MAX aggiunge autorit&agrave; e rete &mdash; utile anche per acquirenti che si spostano da Milano verso nord-ovest.",
        "network_1_p": "Un marchio riconoscibile rassicura proprietari e acquirenti in provincia di Varese.",
        "market_kicker": "Mercato Varesino",
        "market_h2": "Varese cambia zona per zona.",
        "market_intro": "Un immobile a Varese citt&agrave; non segue le stesse dinamiche di Busto, Gallarate o Luino. L'analisi deve essere costruita sulla micro-zona reale.",
        "market_1_span": "Varese citt&agrave;",
        "market_1_h": "Centro e colline",
        "market_1_p": "Qualit&agrave; di vita, verde e domanda stabile da chi lavora tra Varese e Milano.",
        "market_2_span": "Altomilanese",
        "market_2_h": "Busto e Gallarate",
        "market_2_p": "Collegamenti rapidi e mercato dinamico: prezzi che cambiano comune per comune.",
        "market_3_span": "Laghi e nord",
        "market_3_h": "Luino e Prealpi",
        "market_3_p": "Seconda casa e lifestyle: serve capire se il prezzo &egrave; allineato alla zona.",
        "testimonials": [
            ("GL", "Appartamento Varese", "Varese citt&agrave;", "Il posizionamento iniziale era troppo alto per la mia zona. Con analisi OMI e strategia mirata abbiamo chiuso in tempi brevi."),
            ("AT", "Casa con giardino", "Busto Arsizio", "Individuate difformit&agrave; prima delle visite. Vendita conclusa senza sorprese in trattativa."),
            ("RM", "Trilocale", "Gallarate", "Avevo perso tempo con annunci generici. Profilazione acquirenti e prezzo giusto: risultato in poche settimane."),
        ],
        "final_h2": "Prima di vendere in provincia di Varese, serve capire davvero quanto vale.",
        "final_p": "Ti mostro il mercato reale della tua zona e la strategia pi&ugrave; adatta &mdash; prima ancora di parlare di incarico.",
    },
    "lecco": {
        "portrait_span": "RE/MAX &middot; Lecco e Provincia",
        "about_lead": "Conosco il mercato di Lecco, del lago e della Valsassina. Spazio e natura attirano acquirenti, ma i prezzi vanno letti comune per comune.",
        "quote": "&quot;Lecco citt&agrave;, lago e Valsassina non sono lo stesso mercato. Vendere senza micro-analisi significa perdere tempo o lasciare soldi sulla trattativa.&quot;",
        "strategy": "Costruisco una strategia su misura per Lecco, riviera o Valsassina &mdash; prima ancora di pubblicare la prima foto.",
        "method_1_p": "Confronti tra Lecco centro, riviera, Brianza lecchese e Valsassina &mdash; con posizionamento corretto del prezzo.",
        "network_p": "L'affiliazione RE/MAX aggiunge rete e visibilit&agrave; &mdash; anche per acquirenti che arrivano da Milano e Brianza.",
        "network_1_p": "Un marchio riconoscibile rassicura proprietari e acquirenti sul lago e in montagna.",
        "market_kicker": "Mercato Lecchese",
        "market_h2": "Lecco cambia da una valle all'altra.",
        "market_intro": "Un appartamento a Lecco citt&agrave; non segue le stesse dinamiche di Valmadrera, Merate o della Valsassina.",
        "market_1_span": "Lecco e lago",
        "market_1_h": "Centro e riviera",
        "market_1_p": "Domanda solida, prezzi sensibili a vista lago e servizi.",
        "market_2_span": "Brianza lecchese",
        "market_2_h": "Merate e cintura",
        "market_2_p": "Chi esce da Milano cerca equilibrio tra spazio e collegamenti.",
        "market_3_span": "Valsassina",
        "market_3_h": "Montagna",
        "market_3_p": "Qualit&agrave; di vita e seconda casa: i numeri OMI sono ancora pi&ugrave; decisivi.",
        "testimonials": [
            ("LC", "Appartamento Lecco", "Lecco centro", "Prezzo iniziale troppo legato all'emozione del lago. Micro-analisi e strategia: vendita conclusa senza mesi di stallo."),
            ("MR", "Casa in Valsassina", "Ballabio", "Criticit&agrave; tecniche individuate prima del lancio. Trattativa pi&ugrave; fluida e rogito senza intoppi."),
            ("SF", "Trilocale", "Merate", "Il problema non era la casa, ma il target sbagliato. Con profilazione corretta abbiamo chiuso in tempi brevi."),
        ],
        "final_h2": "Prima di vendere a Lecco o in provincia, serve capire davvero quanto vale.",
        "final_p": "Ti mostro il mercato reale della tua zona e la strategia pi&ugrave; adatta &mdash; prima ancora di parlare di incarico.",
    },
    "monza": {
        "portrait_span": "RE/MAX &middot; Monza e Brianza",
        "about_lead": "Seguo il mercato di Monza e Brianza: domanda alta, tempi rapidi e prezzi che cambiano da un comune all'altro.",
        "quote": "&quot;In Brianza il prezzo giusto cambia da Monza a Seregno, da Desio a Vimercate. La micro-zona vale pi&ugrave; di dieci annunci scorrevoli.&quot;",
        "strategy": "Costruisco una strategia su misura per Monza, Seregno, Vimercate o Brianza est &mdash; prima ancora di pubblicare la prima foto.",
        "method_1_p": "Confronti tra Monza centro, comuni di cintura e Brianza est &mdash; con posizionamento corretto del prezzo.",
        "network_p": "L'affiliazione RE/MAX aggiunge rete e visibilit&agrave; &mdash; cruciale in un mercato veloce come la Brianza.",
        "network_1_p": "Un marchio riconoscibile rassicura proprietari e acquirenti in una zona ad alta competizione.",
        "market_kicker": "Mercato Brianza",
        "market_h2": "Monza e Brianza: ogni comune ha il suo ritmo.",
        "market_intro": "Un immobile a Monza non segue le stesse dinamiche di Seregno, Desio o Vimercate. L'analisi deve essere micro-zona per micro-zona.",
        "market_1_span": "Monza",
        "market_1_h": "Centro e ville",
        "market_1_p": "Alta domanda residenziale e forte competizione tra acquirenti.",
        "market_2_span": "Brianza",
        "market_2_h": "Seregno e Desio",
        "market_2_p": "Spazio e collegamenti: mercato veloce con crescite selettive.",
        "market_3_span": "Est Brianza",
        "market_3_h": "Vimercate",
        "market_3_p": "Transizione verso altri mercati lombardi: serve confronto reale zona per zona.",
        "testimonials": [
            ("GL", "Appartamento Monza", "Monza centro", "Mercato rapido: senza numeri giusti rischi di perdere l'acquirente o vendere sottocosto. Strategia e tempismo hanno fatto la differenza."),
            ("MR", "Villa in Brianza", "Seregno", "Tre mesi online senza risultati. Ricalibrato prezzo e comunicazione: chiuso in poche settimane."),
            ("AC", "Trilocale", "Vimercate", "Analisi OMI e verifica documenti prima del lancio. Trattativa senza sorprese."),
        ],
        "final_h2": "Prima di vendere a Monza o in Brianza, serve capire davvero quanto vale.",
        "final_p": "Ti mostro il mercato reale della tua zona e la strategia pi&ugrave; adatta &mdash; prima ancora di parlare di incarico.",
    },
    "sondrio": {
        "portrait_span": "RE/MAX &middot; Sondrio e Valtellina",
        "about_lead": "Conosco le dinamiche della Valtellina: turismo, residenziale e seconda casa hanno logiche di prezzo diverse.",
        "quote": "&quot;Tra Sondrio, Morbegno e le localit&agrave; turistiche, lo stesso immobile pu&ograve; avere logiche di prezzo opposte. La valle conta pi&ugrave; della superficie.&quot;",
        "strategy": "Costruisco una strategia su misura per Sondrio, Valtellina centrale o localit&agrave; turistiche &mdash; prima ancora di pubblicare la prima foto.",
        "method_1_p": "Confronti tra Sondrio citt&agrave;, valli laterali e localit&agrave; alpine &mdash; con posizionamento corretto del prezzo.",
        "network_p": "L'affiliazione RE/MAX aggiunge rete e visibilit&agrave; &mdash; anche per acquirenti da fuori provincia e seconda casa.",
        "network_1_p": "Un marchio riconoscibile rassicura proprietari e acquirenti in Valtellina.",
        "market_kicker": "Mercato Valtellina",
        "market_h2": "Sondrio e provincia: ogni valle ha regole diverse.",
        "market_intro": "Un immobile a Sondrio citt&agrave; non segue le stesse dinamiche di Bormio, Livigno o Morbegno.",
        "market_1_span": "Valtellina centrale",
        "market_1_h": "Sondrio e Morbegno",
        "market_1_p": "Mercato residenziale stabile, prezzi legati a servizi e collegamenti.",
        "market_2_span": "Turismo alpino",
        "market_2_h": "Bormio e Livigno",
        "market_2_p": "Mercato stagionale e premium: analisi OMI ancora pi&ugrave; importante.",
        "market_3_span": "Valli laterali",
        "market_3_h": "Valmalenco",
        "market_3_p": "Seconda casa e lifestyle: attenzione a vincoli e destinazioni d'uso.",
        "testimonials": [
            ("LC", "Appartamento Sondrio", "Sondrio citt&agrave;", "Avevo confuso mercato residenziale e turistico nel prezzo. Analisi corretta e strategia mirata: vendita conclusa regolarmente."),
            ("MR", "Chalet", "Valmalenco", "Vincoli e documenti verificati prima delle visite. Trattativa pi&ugrave; serena."),
            ("SF", "Casa in provincia", "Tirano", "Meschi in online per prezzo fuori mercato. Ricalibrato sulla micro-zona: chiuso in tempi brevi."),
        ],
        "final_h2": "Prima di vendere in Valtellina, serve capire davvero quanto vale.",
        "final_p": "Ti mostro il mercato reale della tua zona e la strategia pi&ugrave; adatta &mdash; prima ancora di parlare di incarico.",
    },
    "cremona": {
        "portrait_span": "RE/MAX &middot; Cremona e Provincia",
        "about_lead": "Seguo il mercato cremonese tra capoluogo, area di Crema e pianura. Anche in provincia tranquilla, la micro-analisi evita errori costosi.",
        "quote": "&quot;Cremona citt&agrave; e Crema non seguono la stessa curva di prezzo. Anche qui, la micro-zona decide.&quot;",
        "strategy": "Costruisco una strategia su misura per Cremona, Crema o pianura &mdash; prima ancora di pubblicare la prima foto.",
        "method_1_p": "Confronti tra Cremona centro, Crema e comuni della pianura &mdash; con posizionamento corretto del prezzo.",
        "network_p": "L'affiliazione RE/MAX aggiunge rete e visibilit&agrave; anche in mercati pi&ugrave; tranquilli della pianura.",
        "network_1_p": "Un marchio riconoscibile rassicura proprietari e acquirenti in provincia di Cremona.",
        "market_kicker": "Mercato Cremonese",
        "market_h2": "Cremona e provincia: tranquilli ma non semplici.",
        "market_intro": "Un immobile a Cremona citt&agrave; non segue le stesse dinamiche di Crema o dei comuni della pianura.",
        "market_1_span": "Cremona citt&agrave;",
        "market_1_h": "Centro e quartieri",
        "market_1_p": "Mercato residenziale stabile, prezzi legati a servizi e stato immobile.",
        "market_2_span": "Area Crema",
        "market_2_h": "Est provincia",
        "market_2_p": "Dinamiche proprie rispetto al capoluogo: confronto OMI essenziale.",
        "market_3_span": "Pianura",
        "market_3_h": "Comuni minori",
        "market_3_p": "Pi&ugrave; spazio e prezzi accessibili, ma attenzione a documenti e conformit&agrave;.",
        "testimonials": [
            ("LC", "Appartamento Cremona", "Cremona centro", "Pensavo bastasse una stima online. L'analisi reale mi ha evitato di uscire con un prezzo fuori mercato."),
            ("MR", "Casa in campagna", "Crema", "Difformit&agrave; individuata prima del lancio. Vendita conclusa senza blocchi al rogito."),
            ("SF", "Trilocale", "Castelleone", "Strategia e tempismo corretti: chiuso senza mesi di attesa inutile."),
        ],
        "final_h2": "Prima di vendere a Cremona o in provincia, serve capire davvero quanto vale.",
        "final_p": "Ti mostro il mercato reale della tua zona e la strategia pi&ugrave; adatta &mdash; prima ancora di parlare di incarico.",
    },
    "lodi": {
        "portrait_span": "RE/MAX &middot; Lodi e Provincia",
        "about_lead": "Seguo il mercato lodigiano: prezzi accessibili ma difformit&agrave; e stato immobile fanno comunque la differenza.",
        "quote": "&quot;In provincia di Lodi il risparmio iniziale non vale nulla se vendi un immobile con problemi tecnici nascosti.&quot;",
        "strategy": "Costruisco una strategia su misura per Lodi citt&agrave; o pianura lodigiana &mdash; prima ancora di pubblicare la prima foto.",
        "method_1_p": "Confronti tra Lodi centro, Codogno e comuni della pianura &mdash; con posizionamento corretto del prezzo.",
        "network_p": "L'affiliazione RE/MAX aggiunge rete e credibilit&agrave; anche in un mercato pi&ugrave; compatto.",
        "network_1_p": "Un marchio riconoscibile rassicura proprietari e acquirenti nel Lodigiano.",
        "market_kicker": "Mercato Lodigiano",
        "market_h2": "Lodi e provincia: attenzione ai dettagli tecnici.",
        "market_intro": "Un immobile a Lodi citt&agrave; non segue le stesse dinamiche dei comuni della pianura.",
        "market_1_span": "Lodi citt&agrave;",
        "market_1_h": "Centro storico",
        "market_1_p": "Mercato compatto, attenzione a stato immobile e servizi.",
        "market_2_span": "Pianura",
        "market_2_h": "Codogno e dintorni",
        "market_2_p": "Prezzi accessibili, verifica tecnica spesso decisiva.",
        "market_3_span": "Collegamenti",
        "market_3_h": "Verso Milano",
        "market_3_p": "Scelte legate agli spostamenti: la zona giusta dipende dai tuoi numeri.",
        "testimonials": [
            ("LC", "Appartamento Lodi", "Lodi centro", "Problemi tecnici scoperti in anticipo grazie alla verifica documentale. Vendita senza sorprese."),
            ("MR", "Casa con giardino", "Codogno", "Prezzo ricalibrato sulla micro-zona: chiuso in tempi brevi."),
            ("SF", "Bilocale", "Casalpusterlengo", "Da mesi online senza risultati. Strategia e target giusti: vendita conclusa."),
        ],
        "final_h2": "Prima di vendere a Lodi o in provincia, serve capire davvero quanto vale.",
        "final_p": "Ti mostro il mercato reale della tua zona e la strategia pi&ugrave; adatta &mdash; prima ancora di parlare di incarico.",
    },
    "mantova": {
        "portrait_span": "RE/MAX &middot; Mantova e Provincia",
        "about_lead": "Seguo il mercato mantovano tra centro UNESCO, pianura e confine con Veneto ed Emilia.",
        "quote": "&quot;Mantova citt&agrave; e i comuni della pianura non condividono la stessa domanda. La micro-zona va letta con attenzione.&quot;",
        "strategy": "Costruisco una strategia su misura per Mantova centro, pianura o zona confine &mdash; prima ancora di pubblicare la prima foto.",
        "method_1_p": "Confronti tra Mantova centro, Suzzara e comuni della pianura &mdash; con posizionamento corretto del prezzo.",
        "network_p": "L'affiliazione RE/MAX aggiunge rete e visibilit&agrave; anche in un mercato influenzato da pi&ugrave; regioni.",
        "network_1_p": "Un marchio riconoscibile rassicura proprietari e acquirenti in provincia di Mantova.",
        "market_kicker": "Mercato Mantovano",
        "market_h2": "Mantova e provincia: cultura e pianura.",
        "market_intro": "Un immobile in centro storico non segue le stesse dinamiche dei comuni della pianura.",
        "market_1_span": "Mantova citt&agrave;",
        "market_1_h": "Centro UNESCO",
        "market_1_p": "Appeal culturale e residenziale, prezzi legati a tipologia e posizione.",
        "market_2_span": "Pianura",
        "market_2_h": "Comuni sparsi",
        "market_2_p": "Pi&ugrave; spazio, attenzione a bonifiche e conformit&agrave;.",
        "market_3_span": "Confini",
        "market_3_h": "Suzzara e sud",
        "market_3_p": "Mercato influenzato anche da Veneto ed Emilia: serve confronto reale.",
        "testimonials": [
            ("LC", "Appartamento Mantova", "Mantova centro", "Centro storico con criticit&agrave; urbanistiche individuate prima del lancio. Trattativa fluida."),
            ("MR", "Casa in pianura", "Suzzara", "Prezzo apparentemente conveniente ma con rischi tecnici. Analisi completa prima di uscire sul mercato."),
            ("SF", "Trilocale", "Virgilio", "Strategia mirata e acquirenti profilati: vendita conclusa senza stallo."),
        ],
        "final_h2": "Prima di vendere a Mantova o in provincia, serve capire davvero quanto vale.",
        "final_p": "Ti mostro il mercato reale della tua zona e la strategia pi&ugrave; adatta &mdash; prima ancora di parlare di incarico.",
    },
    "pavia": {
        "portrait_span": "RE/MAX &middot; Pavia e Provincia",
        "about_lead": "Seguo il mercato pavese tra universit&agrave;, Oltrep&ograve; e Lomellina. Tre mercati diversi, una sola regola: analisi prima del prezzo.",
        "quote": "&quot;Pavia citt&agrave;, Oltrep&ograve; e Lomellina sono tre mercati diversi. Vendere senza micro-analisi significa lasciare soldi sulla trattativa.&quot;",
        "strategy": "Costruisco una strategia su misura per Pavia, Oltrep&ograve; o Lomellina &mdash; prima ancora di pubblicare la prima foto.",
        "method_1_p": "Confronti tra Pavia centro, Oltrep&ograve; e Lomellina &mdash; con posizionamento corretto del prezzo.",
        "network_p": "L'affiliazione RE/MAX aggiunge rete e visibilit&agrave; su un territorio molto eterogeneo.",
        "network_1_p": "Un marchio riconoscibile rassicura proprietari e acquirenti in provincia di Pavia.",
        "market_kicker": "Mercato Pavese",
        "market_h2": "Pavia e provincia: citt&agrave;, collina e pianura.",
        "market_intro": "Un immobile a Pavia citt&agrave; non segue le stesse dinamiche di Vigevano, Oltrep&ograve; o Lomellina.",
        "market_1_span": "Pavia citt&agrave;",
        "market_1_h": "Universit&agrave;",
        "market_1_p": "Domanda stabile, mercato influenzato da locazioni e famiglie.",
        "market_2_span": "Oltrep&ograve;",
        "market_2_h": "Collina",
        "market_2_p": "Seconda casa e lifestyle: prezzi legati a micro-borgo e accessi.",
        "market_3_span": "Lomellina",
        "market_3_h": "Pianura",
        "market_3_p": "Prezzi pi&ugrave; accessibili, verifica tecnica spesso decisiva.",
        "testimonials": [
            ("LC", "Appartamento Pavia", "Pavia centro", "Universit&agrave; e residenziale: target sbagliato all'inizio. Strategia corretta e vendita in tempi brevi."),
            ("MR", "Cascina Oltrep&ograve;", "Broni", "Mercato collina con prezzo emotivo. Analisi OMI e posizionamento giusto prima del lancio."),
            ("SF", "Trilocale", "Vigevano", "Documenti e conformit&agrave; verificati in anticipo. Rogito senza intoppi."),
        ],
        "final_h2": "Prima di vendere a Pavia o in provincia, serve capire davvero quanto vale.",
        "final_p": "Ti mostro il mercato reale della tua zona e la strategia pi&ugrave; adatta &mdash; prima ancora di parlare di incarico.",
    },
}


def build_testimonials_html(items: list[tuple[str, str, str, str]]) -> str:
    cards = []
    for avatar, title, zone, text in items:
        cards.append(
            f"""          <article class="testimonial-card reveal">
            <div class="stars">&#9733;&#9733;&#9733;&#9733;&#9733;</div>
            <p>{text}</p>
            <div class="person"><div class="avatar">{avatar}</div><div><strong>{title}</strong><span>{zone}</span></div></div>
          </article>"""
        )
    return "\n".join(cards)
